apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-example-cfg
  labels:
    app: webhook-example
webhooks:
  - name: tunde.meetup.com
    clientConfig:
      service:
        name: webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: 
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments"]
    namespaceSelector:
      matchLabels:
        webhook-example: enabled